version: '3'

services:
  data_extractor:
    container_name: twinpack-mosquitto
    image: docker-net-data_extractor:1.0.0
    ports:
      - "502:502"
      - "135:135"
    networks:
      - my_network
    # Add other configuration options if needed

  data_manager:
    container_name: twinpack-mosquitto
    image: docker-net-data_manager:1.0.0
    ports:
      - "27017:27017"
    networks:
      - my_network
    # Add other configuration options if needed

  mosquitto:
    container_name: twinpack-mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    networks:
      - my_network
    # Add other configuration options if needed

  mongo_db:
    container_name: twinpack-mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - my_network
    # Add other configuration options if needed
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: mqtt

networks:
  my_network:
    driver: bridge
